// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/26/2025, 12:50:55 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/plugins/**/*.{js,ts,mjs}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/composables/**/*.{js,ts,mjs}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/utils/**/*.{js,ts,mjs}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/pages/index.vue","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/pages/login.vue","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/pages/calendar.vue","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/pages/dashboard.vue","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;