// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/25/2025, 11:51:16 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/plugins/**/*.{js,ts,mjs}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/composables/**/*.{js,ts,mjs}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/utils/**/*.{js,ts,mjs}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/pages/index.vue","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/pages/login.vue","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/pages/calendar.vue","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Soren/Desktop/Sites/Calendar_App_Chocov3/REFACTORED_CODEBASE/backup_20250425_222038/app.config.{js,ts,mjs}"]}},
{"content":["components/**/*.{vue,js,ts}","layouts/**/*.vue","pages/**/*.vue","composables/**/*.{js,ts}","plugins/**/*.{js,ts}","App.{js,ts,vue}","app.{js,ts,vue}","Error.{js,ts,vue}","error.{js,ts,vue}","content/**/*.md"]},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;